### ISSUE TITLE
[Bug]使用account.session调用guild_member_mute时报错satori.exception.BadRequestException: 400 bad request

### ISSUE THREAD

**Issue by YuelaoOmega** [RF-Tar-Railt/satori-python#10]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个Bug

# Bug

## 问题
使用account.session调用guild_member_mute时报错satori.exception.BadRequestException: 400 bad request
解析 guild.member.mute 请求时出现问题，来自 127.0.0.1。	问题 1：#/required：应当有必需属性 channel_id
我在填齐了这几个参数的情况下仍然报了这个错

## 如何复现

import satori
from satori import Event,WebsocketsInfo
from satori.client import Account
from satori import EventType

bot = satori.client.App(WebsocketsInfo(port=5501,token='-'))

@bot.register_on(EventType.MESSAGE_CREATED)
async def Message_(account,event):
    if event and event.user.id != event.self_id and not bool(event.channel.type):
        if MessageRaw == "/禁言自己":
            await account.session.guild_member_mute(guild_id=event.guild.id,user_id=event.user.id,duration=3000000)

## 预期行为
在调用后可以成功的禁言

## 使用环境:
-操作系统 (Windows/Linux/Mac):
Windows 10 专业版 22H2
19045.2908

-Python 版本:
Python 3.11.4

-SDK 版本:
0.12.0

-使用的 Satori 服务端 (例如 Chronocat):
Chronocat

## 日志/截图

![QQ截图20240607215008](https://github.com/RF-Tar-Railt/satori-python/assets/141794292/7737c97d-9088-46f5-a6b3-304baa5241d3)

**Comment by RF-Tar-Railt** [comment]
根据satori标准 guild.member.mute 接口不需要 channel_id
所以这个是 chronocat的问题，请转交给 chronocat
