### ISSUE TITLE
[Bug] 好像没有GuildMember这个类

### ISSUE THREAD

**Issue by hhhhhge** [RF-Tar-Railt/satori-python#12]
## 请确认：

* [ ] 问题的标题明确
* [ ] 我翻阅过其他的 issue 并且找不到类似的问题
* [ ] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个Bug

# Bug

## 使用环境:
- 操作系统 (Windows/Linux/Mac):
- Python 版本: 
- SDK 版本:
- 使用的 Satori 服务端 (例如 Chronocat):

**Comment by RF-Tar-Railt** [comment]
？
这边叫Member啊
