### ISSUE TITLE
[Bug] 收到群聊事件后报错 Caused by TypeError("__init__() got an unexpected keyword argument 'nick'")

### ISSUE THREAD

**Issue by super1207** [RF-Tar-Railt/satori-python#4]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个Bug

# Bug

## 问题

我尝试对接我的satori适配器：https://github.com/super1207/satoricq
我用适配器向satori-python发送了一个消息事件，然后satori-python报了这个错误：
![image](https://github.com/RF-Tar-Railt/satori-python/assets/30586004/1ab90594-fee8-486e-bb03-f9acba4c5482)

看起来像是我发送的事件中多出了nick字段？但是这是在 https://satori.js.org/zh-CN/resources/user.html#user 中允许存在的

## 如何复现

发送如下格式的消息事件给satori-python：
```{"op": 0, "body": {"id": 0, "type": "message-created", "platform": "satori", "self_id": "2044078478", "timestamp": 1701842313000, "channel": {"id": "GROUP_7021447456313511", "type": 0}, "guild": {"id": "GROUP_7021447456313511"}, "member": {"nick": "super1208", "avatar": "https://img.kookapp.cn/avatars/2023-07/SkpJ5zCSXn06j06j.png?x-oss-process=style/icon", "joined_at": 1675500752000}, "message": {"id": "-1347721390", "content": "\u4f60\u597d", "created_at": 1701842313000}, "role": {"id": "owner", "name": "owner"}, "user": {"id": "2139689190", "name": "super1207", "nick": "super1207", "avatar": "https://img.kookapp.cn/avatars/2023-07/SkpJ5zCSXn06j06j.png?x-oss-process=style/icon"}}}```

## 预期行为

不报错，正常解析。

## 使用环境:
- 操作系统 (Windows/Linux/Mac):windows
- Python 版本: Python 3.8.10 64bit
- SDK 版本:satori-python 0.8.0 我使用pip install来安装的
- 使用的 Satori 服务端 (例如 Chronocat):https://github.com/super1207/satoricq

## 日志/截图
见问题

**Comment by RF-Tar-Railt** [comment]
https://github.com/RF-Tar-Railt/satori-python/releases/tag/v0.9.2

**Comment by super1207** [comment]
thanks，已经测试了，可以正常工作
