### ISSUE TITLE
[Bug] satori-python无法解析Chronocat发送的Quote消息和私聊信息

### ISSUE THREAD

**Issue by half-nothing** [RF-Tar-Railt/satori-python#5]
## 请确认：
* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个Bug
* [x] 已经验证过官方ts实现的客户端适配器，可以解析，即排除服务端问题 

# Bug
如题

## 问题
如题

## 如何复现
安装好基础环境以后，直接回复消息和私聊既可复现

## 预期行为
调用MessageObject的message属性后，应当返回Elements列表

## 使用环境:
- 操作系统 (Windows/Linux/Mac): Windows10 
- Python 版本: 3.12.2
- SDK 版本: 0.11.1
- 使用的 Satori 服务端 (例如 Chronocat): Chronocat
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/edd9cc63-0853-4e36-b942-78a871f77f3f)

## 日志/截图   
`官方ts实现的客户端适配器`
`quote消息`
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/f7b67311-a57f-4881-b519-b77f5a907c62)
`私聊消息`
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/25aab16a-5f21-4363-8bcb-caec617283fe)
---
`quote消息解析失败`
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/b5029481-0780-4677-aaad-ef800f128f84)
`私聊消息解析失败`
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/eb46b583-52f5-40e6-8c94-a56e7707fe01)

**Comment by RF-Tar-Railt** [comment]
https://github.com/RF-Tar-Railt/satori-python/releases/tag/v0.11.2

**Comment by RF-Tar-Railt** [comment]
至于这个私聊事件，你把raw发出来看看

**Comment by half-nothing** [comment]
> 至于这个私聊事件，你把raw发出来看看

{"op":0,"body":{"id":1812,"type":"message-created","platform":"chronocat","self_id":"123456","timestamp":1711807248000,"user":{"id":"123456","avatar":"http://thirdqq.qlogo.cn/headimg_dl?dst_uin=123456&spec=640"},"channel":{},"message":{"id":"7352156147280594561","content":"ttt"}}}

**Comment by RF-Tar-Railt** [comment]
`"channel":{}` channel为什么是空的，satori协议里 Channel 的 id 和 type 都是必需参数

**Comment by half-nothing** [comment]
我知道你很急，但你先别急，问题还在呢
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/07e24847-dc44-4f9e-8c19-daba92493b39)
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/4243e0a3-422e-4d26-9bd3-b6a19118c033)

**Comment by RF-Tar-Railt** [comment]
哎chronocat

**Comment by half-nothing** [comment]
> 哎chronocat

一天一个issue，一天一个bug
![181f30413e6ab3a67bf577a4c1e17976](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/29b20640-2bae-40a4-8497-2418507cd11e)

**Comment by half-nothing** [comment]
我先自己暴力改一版用着
还有改的时候又双叒叕发现一个问题
Author里面名字字段改成了name
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/f88356a7-8c11-4aa0-98f4-edd99c6000c1)
![image](https://github.com/RF-Tar-Railt/satori-python/assets/50048293/bf7415e8-d390-45e4-b1ba-994100df2f2d)
